### ISSUE TITLE
Allow the use of Alertmanager V2

### ISSUE THREAD

**Issue by wilfriedroset** [ovh/terraform-provider-mimirtool#27]
Following Mimir update for alertmanager v2 in https://github.com/grafana/mimir/pull/7103 we should allow users to specify with API path to use for alertmanager, either v1 or v2. the default value should be v1 to avoid breaking change but clarify that it is deprecated.

**Comment by vaxvms** [comment]
terraform-provider-mimirtool relies on alertmanager tenant configuration endpoints provided by mimir under /api/v1/alerts.

this PR change version for endpoints under /alertmanager/api

**Comment by vaxvms** [comment]
Closing
